config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

resources :adventures do
  resources :bookings
end

resources :adventures
get "/profil", to: "pages#profil"

  # Defines the root path route ("/")
  # root "articles#index"
end

# booking.owner_id = Adventure.user.id
# booking.user_id = current_user

app/models/adventure.rb
class Adventure < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :adventure
end

app/models/user.rb
class User < ApplicationRecord
  has_many :adventures
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  before_action :set_adventure, only: [:show, :destroy]


  def new
    @adventure = Adventure.new
  end

  def show
    @adventure = Adventure.find(params[:id])
    @booking = Booking.new

  end

  def create
    @adventure = Adventure.new(adventure_params)
    @adventure.user = current_user
    if @adventure.save!
      redirect_to adventure_path(@adventure)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @adventure.destroy
    redirect_to adventure_path, status: :see_other
  end

  private

  def adventure_params
    params.require(:adventure).permit(:title, :price, :location, :decription, photos: [])
  end

  def set_adventure
    @adventure = Adventure.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @adventure = Adventure.find(params[:adventure_id])
    @user = current_user
  end

  def create
    @user = current_user
    @adventure = Adventure.find(params[:adventure_id])
    @booking = Booking.new(booking_params)
    @booking.adventure = @adventure
    @booking.user = current_user
    if @booking.save
      redirect_to profil_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @adventures = Adventure.all
  end

  def profil; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# def new
#   @user = User.new
# end

# def create
#   @user = User.new(user_params)
#   if @user.save
#     redirect_to adventure_path(@adventure)
#   else
#     render :new, status: :unprocessable_entity
#   end
# end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adventures/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-black rounded p-3 shadow text-white">
        <h3>Create a new adventure</h3>
        <%= simple_form_for @adventure do |f| %>
          <%= f.input :title, placeholder: 'title' %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <%= f.input :price, placeholder: 'price' %>
          <%= f.input :location, placeholder: 'location' %>
          <%= f.input :decription, placeholder: 'description' %>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/adventures/show.html.erb
<div class="row">
  <div class="col-12">
    <div class="img-fluid"  style="width: 50rem; ">
      <div class ="container_imgs">
        <img src = "<%=@adventure.photos.third.url%>" class = "card-img-top" height=300 width=250 alt="...">
        <div class ="image_right">
            <img src = "<%=@adventure.photos.first.url%>"class = "card-img-top" height=300 width=250 alt="...">
        </div>
        <div class ="image_left">
            <img src = "<%=@adventure.photos.second.url%>" class = "card-img-top" height=300 width=250 alt="...">
        </div>
      </div>
    </div>

    <div class = "row col-8">
      <ul class ="list-group list-group-flush">
        <div class = "title-body">
            <li class = "list-group"> <%= @adventure.title %> <i class="bi bi-person-circle"> </li>
        </div>
        <div class = "card_description p-3">
          <li class = "list-group-item"> <%= @adventure.decription %>  </li>
          <li class = "list-group-item"> Location: <%= @adventure.location %> </li>
          <li class = "list-group-item"> duration: <%= @adventure.duration %> </li>
          <li class = "list-group-item"> Price: <%= @adventure.price %> $ </li>

        </div>
      </ul>



    <section class="portfolio-experiment">
  <a>
    <span class="text"><%= link_to "Book this adventure", new_adventure_booking_path(@adventure)%></span>
    <span class="line -right"></span>
    <span class="line -top"></span>
    <span class="line -left"></span>
    <span class="line -bottom"></span>
  </a>
</section>

  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="bg-black rounded p-3 shadow text-white">
    <div class="form-wrapper">
      <h2>Book this adventure</h2>
      <%= simple_form_for [@adventure, @booking],data: { controller: 'flatpickr' } do |f| %>
        <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
        <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
        <%= f.submit 'Book this adventure' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
<%= render "shared/navbar" %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="kl">KOH-LANTA ADVENTURE</h1>

<p class= "descr">Rent a incredible adventure from all over the world... and beyond</p>

<%# <%= link_to "Create a new adventure", new_adventure_path, class: "btn btn-flat" %>


<div class="container">

  <div class="cards">
  <% @adventures.each do |adventure| %>

  <div class="card m-3">
    <%= link_to adventure_path(adventure), :action => 'go' do %>

      <%if adventure.photos.attached?%>
        <%= cl_image_tag(adventure.photos.first.key, :transformation=>[
        {:height=>300, :width=>250, :crop=>"scale"},
        ]) %>
      <% end %>
      <li class="ms-2"> <%= adventure.title %></li>
      <li class="ms-2"> <%= adventure.location %></li>
      <li class="ms-2"> <%= adventure.duration %></li>
      <li class="ms-2"> Price: <%= adventure.price %> $</li>

    <% end %>
</div>
  <% end %>
</div>
<div>

  <section class="portfolio-experiment mb-3">
  <a>
    <span class="text"><%= link_to "create this adventure", new_adventure_path, class: "btn-shiny" %></span>
    <span class="line -right"></span>
    <span class="line -top"></span>
    <span class="line -left"></span>
    <span class="line -bottom"></span>
  </a>
</section>

</div>

app/views/pages/profil.html.erb
<div class="container">
  <div class="text-white">

    <h3 class="avatar_username"><%= image_tag "https://res.cloudinary.com/dtlwkdqpv/image/upload/v1677676328/denis-brogniart_ehh2nh.jpg", class: "avatar-denis", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %><%= current_user.username %></h3>

    <%#= current_user.adventures.each do |adventure| %>
      <%#= aventure.location %>
    <%# end %>
  </div>
</div>
<div class="container">
  <div class="other pt-3">
    <%= link_to "Create a new adventure", new_adventure_path, class: "btn btn-dark" %>
  </div>

  <div class="row justify-content-envenly mt-4">
    <div class="title-cards col-6">
      <h3>My adventures</h3>
    </div>
    <div class="title-cards col-6">
      <h3>My reservations</h3>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-envenly mt-2">
    <div class="dashboard-cards col-6">
      <% current_user.adventures.each do |adventure| %>

        <div class="dashboard-card">
          <%= link_to adventure_path(adventure), :action => 'go' do %>

            <%if adventure.photos.attached?%>
              <%= cl_image_tag(adventure.photos.first.key, :transformation=>[
              {:height=>300, :width=>250, :crop=>"scale"},
              ]) %>
            <% end %>
            <li class="ms-2"> <%= adventure.title %></li>
            <li class="ms-2"> <%= adventure.location %></li>
            <li class="ms-2"> <%= adventure.duration %></li>
            <li class="ms-2"> Price: <%= adventure.price %> $</li>
            <li class="ms-2"><%= link_to "", adventure_path(adventure), class: "fa-regular fa-trash-can", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this adventure?" } %></li>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="dashboard-cards col-6">
      <% unless current_user.bookings.empty? %>

        <% current_user.bookings.each do |booking| %>

          <div class="dashboard-card">
            <%= link_to adventure_path(booking.adventure), :action => 'go' do %>

              <%if booking.adventure.photos.attached?%>
                <%= cl_image_tag(booking.adventure.photos.first.key, :transformation=>[
                {:height=>300, :width=>250, :crop=>"scale"},
                ]) %>
              <% end %>
              <li class="ms-2"> <%= booking.adventure.title %></li>
              <li class="ms-2"> <%= booking.adventure.location %></li>
              <li class="ms-2"> <%= booking.start_date %></li>
              <li class="ms-2"> <%= booking.end_date %></li>
              <li class="ms-2"><%= link_to "", profil_path, class: "fa-regular fa-trash-can", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this adventure?" } %></li>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dtlwkdqpv/image/upload/v1677671654/logo_jkx3ql.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <%# <p class="title_navbar">Koh-Lanta</p> %>
      <%= link_to "Koh-Lanta", root_path, class: "title_navbar" %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">

            <%= current_user.username %>

          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dtlwkdqpv/image/upload/v1677676328/denis-brogniart_ehh2nh.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <%= link_to "Dashboard", profil_path, class: "dropdown-item" %>

              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>